### ISSUE TITLE
Formatters extension / discussion

### ISSUE THREAD

**Issue by robjens** [repocho/raml-mocker#14]
I've been working, experimenting with and thinking about mocking (raml) API data. I've come to the conclusion that, although faker is nice, a lot nicer is [chance.js](http://chancejs.com/). One of the reasons is the functions are a lot more sophisticated (but normalized, through option map arguments, normally they would be unary fns taking 0 or 1 argument).

The problem with the current architecture we have, mainly `formats.js` contains a literal mapping from our fns to fakers. Perhaps back then (I'm talking the ~v1 faker here) it was manageable due to the small amount of functions present but at the current time it is cumbersome to write them all for ourselves (in this library) as well as expect the user to do so.

I was inspired mostly by work done here: https://github.com/json-schema-faker/json-schema-faker/blob/master/lib/util/container.js

What I do not really like about their solution is that they use the schema keywords for each lib, so e.g. calling a faker function would take something like:

``` json
"faker" : "somefn"
```

and chance would take:

``` json
"chance" : "somefn"
```

I am not really sure how they pass arguments though. Personally, I'd think the following might be a (more, but I'm biased of course) elegant solution:

``` json
"mock" : {"func" : "faker.somefn.we.map.by.name",
          "args" : {"min": 40, "max": 120}}
```

Question is how one would want to expose this. I am not sure if raw (`faker["somefn"]["we"]["map"]["by"]["name"]`) access is a great idea but on the other hand, few harmful functions in those libraries. Pretty much all is geared towards, well duh, generating random data. Most are functions at about 1 level deep from the root of the main library exported object or function. Further limiting allowed selection (through JSON Schemas) to functions (as you already do the normal/lower-case check for functions) and allowing calls to root or first level nested functions could be mapped dynamically or, called directly via string reference (I guess the functional JS way would be to just split on the dots and reduce the properties from the object) as I demonstrated, using square bracket notation.

Another option, is to 'map' the object property structure a bit more:

``` json
"mock" : { "faker": {"company" : {"companyName": {"min-words": 3, "max-words": 6}}}}
```

More typing, twice the amount of brackets/nesting we need but more closely resembles the actual object structure (so in this case, we might take faker/chance/any-other-lib). One might remove the "mock" even but I like it because mostly, it is unambiguous and can be easily be spotted by people less familiar with JSON Schema (and what belongs there, what doesn't).

I've been hacking in Clojure the past few years btw, and recently active with Node again but I use wisp since my brain really loves polish notation so much better now... reading JS is hard, writing it (good) is a pain which is and why (time constraints as well) I haven't come up with a working prototype yet - I also realized `format.js` has faker baked in hard and one might not want to break existing functionality (functions expecting (faker, schema) to be passed. Another option would be (perhaps also why `mock` as a schema key is convenient) to have a second one on the side for backwards compatibility.

**Comment by repocho** [comment]
There is a initiative to build a better Stub REST API server out of the box. You can check the status here:
https://github.com/json-schema-faker/json-schema-faker/issues/145

Thanks and sorry about that delay ! I didn't have the time to give you a proper reply.

**Comment by robjens** [comment]
@repocho Awesome, thanks for the feedback... no worries about the delays, I know everything about them (as this is about half a year later ;) I'll close this, again, much appreciated
