### ISSUE TITLE
The schema parser should be able to import external schema files

### ISSUE THREAD

**Issue by repocho** [repocho/raml-mocker#2]
The schema parser should be able to import external schema files.

The problem of this issue is knowing the path of the parsed raml file. The parser plugin should provide the path of the raml or the path of the schema file.

The easiest part of this issue is to load external schemas with uri like:
http://mydomain.com/subSchema

**Comment by alvassin** [comment]
+1. A big pain in the ass. raml-mocker tries to import relative schema imports via $ref from main folder, not from subfolder.

**Comment by alvassin** [comment]
Referencing [PR](https://github.com/raml-org/raml-js-parser/pull/176) with fix.

**Comment by repocho** [comment]
So now raml-parser provides the current folder of the file ?

Could you please do a PR with the needed changes @alvassin ?

**Comment by alvassin** [comment]
@repocho Raml does not provide current folder of the file, i've just added option `dereferenceSchemas=true`, which enforces dereferencing of all schemas. If this solution suits you, you need to pull latest version from raml-js-parser & use `dereferenceSchemas=true` option when loading raml file.

**Comment by repocho** [comment]
**So !!**
If I understand well, if we use `{ dereferenceSchemas: true }` loading a raml file, it will retrieve all `$refs` correctly from the schemas inside the raml files and also will retrieve all the $refs inside the json schema files.

So the result will be a json without $ref attributes at all, right ?

If I'm right I can remove from `raml-mocker` all the related code of "$ref" attribute.

**Comment by alvassin** [comment]
@repocho right, it should work so.

**Comment by repocho** [comment]
Great !!! I'm testing it and works like a charm !!

Thanks for your help and your PR to raml-parser @alvassin !!

**Comment by repocho** [comment]
@alvassin I have detected that circular dependencies are not allowed but could be valid. If array elements `children` is 0 it will stop.

For example:
```javascript
{
    "$schema": "http://json-schema.org/schema",
    "definitions": {
        "node": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "format": "id"
                },
                "label": {
                    "type": "string"
                },
                "children": {
                    "type": "array",
                    "items": {
                        "$ref_circular": "#/definitions/node"
                    }
                }
            },
            "required": ["id", "label", "children"]
        }
    },
    "items": {
        "$ref": "#/definitions/node"
    },
    "type": "array"
}
```

What do you think it's the best way to solve this??

**Comment by repocho** [comment]
I've opened another issue for that: #20
